# This is a configuration file for the ResNet-18 model
name: "lenet5"

# Dataset Params
dataset: "mnist"
train_path: None
test_path: None
num_workers: 16
distributed: False
batch_size: [128,5120] # train, test

# Training Params
epochs: 80
nc: 10 # number of classes

backbone:
  # [from, repeats, module, args]
  - [-1, 1, QuantConv2d, "conv1", {'in_channels':1, 'out_channels':6, 'kernel_size':5, 'stride':1, 'padding':0, 'bias':False, 'weight_quant': LearnedBitWidthQuantizer}]
  - [-1, 1, BatchNorm2d, "bn1", {'num_features':6, 'eps':0.00001, 'momentum':0.1, 'affine':True, 'track_running_stats':True}]
  - [-1, 1, QuantReLU, "relu1", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
  - [-1, 1, QuantMaxPool2d, "pool1", {'kernel_size':2, 'stride':2, 'padding':0, 'dilation':1, 'ceil_mode':False}]
  - [-1, 1, QuantConv2d, "conv2", {'in_channels':6, 'out_channels':16, 'kernel_size':5, 'stride':1, 'padding':0, 'bias':False, 'weight_quant': LearnedBitWidthQuantizer}]
  - [-1, 1, BatchNorm2d, "bn2", {'num_features':16, 'eps':0.00001, 'momentum':0.1, 'affine':True, 'track_running_stats':True}]
  - [-1, 1, QuantReLU, "relu2", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
  - [-1, 1, QuantMaxPool2d, "pool2", {'kernel_size':2, 'stride':2, 'padding':0, 'dilation':1, 'ceil_mode':False}]
  - [-1, 1, QuantLinear, "fc1", {'in_features':256, 'out_features':120, 'bias':False}]
  - [-1, 1, QuantReLU, "relu3", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
  - [-1, 1, QuantLinear, "fc2", {'in_features':120, 'out_features':84, 'bias':False}]
  - [-1, 1, QuantReLU, "relu4", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
  - [-1, 1, QuantLinear, "fc3", {'in_features':84, 'out_features':10, 'bias':False}]
  - [-1, 1, Softmax, "softmax", {'dim':1}]

