[build-system]
requires = ["setuptools>=42", "wheel", "brevitas"]
build-backend = "setuptools.build_meta"

[project]
name = "synapselab"
version = "0.1.0"
description = "Framework for training and optimizing neural networks"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
    { name = "Michael Mecik", email = "michael.mecik@informatik.hs-fulda.de" }
]

[tool.setuptools.packages.find]
where = ["."]
include = ["synapselab*"]
