"""Build an experiment config (exp_config.yaml) from GUI choices.

The flow the GUI drives: pick a network description (a model yaml), pick a
dataset, configure training -> this assembles the experiment yaml that ties them
together (the same shape as configs/experiments/*.yaml). The model yaml holds the
actual net; the experiment yaml references it via `model:` plus dataset + training.

Pure stdlib + pyyaml, so it is testable without torch. The dataset list falls
back to a static set of registered names when the (torch-heavy) dataset registry
can't be imported.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

# registered dataset names, used when the torch-importing registry isn't available
_FALLBACK_DATASETS = [
    "cifar10", "mnist", "fashion_mnist", "imagenet", "imagefolder", "jsc", "openml",
    "coco", "yolo",
]


def list_datasets() -> List[str]:
    try:
        from src.datasets.factory import list_datasets as _reg
        import src.datasets  # noqa: F401  (triggers the @register_dataset decorators)
        names = _reg()
        return names or _FALLBACK_DATASETS
    except Exception:
        return _FALLBACK_DATASETS


def list_models(repo_root: str) -> List[str]:
    base = Path(repo_root) / "configs" / "models"
    if not base.exists():
        return []
    return sorted(str(p.relative_to(repo_root)) for p in base.rglob("*.yaml"))


def read_model(repo_root: str, rel_path: str) -> str:
    """Return the raw text of a model (network) yaml -- 'open the net description'."""
    p = (Path(repo_root) / rel_path).resolve()
    root = Path(repo_root).resolve()
    if root not in p.parents and p != root:        # keep reads inside the repo
        raise ValueError("path escapes the repository")
    if not p.exists():
        raise FileNotFoundError(rel_path)
    return p.read_text()


def build_exp_config(spec: Dict[str, Any]) -> Dict[str, Any]:
    """Assemble an experiment-config dict from a GUI spec.

    Required: name, model (path to a model yaml), dataset.
    Everything else has a sensible default derived from the name.
    """
    name = str(spec.get("name", "")).strip()
    model = str(spec.get("model", "")).strip()
    dataset = str(spec.get("dataset", "")).strip()
    if not name:
        raise ValueError("experiment name is required")
    if not model:
        raise ValueError("a model yaml (network description) is required")
    if not dataset:
        raise ValueError("a dataset is required")

    output_dir = str(spec.get("output_dir") or f"./outputs/{name}")

    bs = spec.get("batch_size", [128, 256])
    if isinstance(bs, int):
        bs = [bs, bs]
    bs = [int(bs[0]), int(bs[1])]

    cfg: Dict[str, Any] = {
        "name": name,
        "model": model,
        "dataset": dataset,
        "num_workers": int(spec.get("num_workers", 4)),
        "distributed": bool(spec.get("distributed", False)),
        "batch_size": bs,
        "epochs": int(spec.get("epochs", 30)),
        "learning_rate": float(spec.get("learning_rate", 0.01)),
        "output_dir": output_dir,
        "best_metric_name": str(spec.get("best_metric_name", "accuracy")),
        "best_metric_mode": str(spec.get("best_metric_mode", "max")),
        "validate_every": int(spec.get("validate_every", 1)),
        "tracking_db": str(spec.get("tracking_db") or f"{output_dir}/experiments.db"),
    }
    # train_path is optional (torchvision datasets cache there; JSC/OpenML don't need it)
    train_path = spec.get("train_path")
    if train_path:
        cfg["train_path"] = str(train_path)
    return cfg


def to_yaml(cfg: Dict[str, Any]) -> str:
    header = (f"# Experiment config generated by the axionlab GUI.\n"
              f"# Net: {cfg.get('model')} | dataset: {cfg.get('dataset')}\n")
    body = yaml.safe_dump(cfg, sort_keys=False, default_flow_style=False)
    return header + body


def default_path(repo_root: str, name: str) -> str:
    """Where a generated experiment yaml lands by default (relative to repo)."""
    return str(Path("configs") / "experiments" / "generated" / f"{name}.yaml")


def save_exp_config(repo_root: str, cfg: Dict[str, Any], rel_path: Optional[str] = None,
                    overwrite: bool = False) -> Dict[str, Any]:
    rel = rel_path or default_path(repo_root, cfg["name"])
    dest = (Path(repo_root) / rel).resolve()
    root = Path(repo_root).resolve()
    if root not in dest.parents:                   # keep writes inside the repo
        raise ValueError("path escapes the repository")
    existed = dest.exists()
    if existed and not overwrite:
        raise FileExistsError(rel)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(to_yaml(cfg))
    return {"path": str(dest.relative_to(root)), "overwritten": existed}
