# This is a configuration file for the jsc_2l model
name: "jsc_2l"

# Dataset Params
dataset: "jsc"
train_path: None
test_path: None
num_workers: 16
distributed: False
batch_size: [1024,1024] # train, test
dataset_root_path: "/tmp/datasets/jsc/processed-pythia82-lhc13-all-pt1-50k-r1_h022_e0175_t220_nonu_truth.z"
lsb_in: -8
lsb_out: -8

# Training Params
epochs: 80
nc: 5 # number of classes

backbone:
  # [from, repeats, module, args]
- [ -1, 1, Linear, "dense1", { 'in_features': 16, 'out_features': 32, 'bias': True } ]
- [ -1, 1, ReLU, "relu1", { 'inplace': True } ]
- [ -1, 1, Linear, "dense2", { 'in_features': 32, 'out_features': 5, 'bias': True } ]
- [ -1, 1, Softmax, "softmax", { 'dim': 1 } ]