name: quant_jsc_xl
dataset: jsc
train_path: None
test_path: None
num_workers: 16
distributed: False
batch_size:
 - 4196
 - 4196
dataset_root_path: /tmp/datasets/jsc/processed-pythia82-lhc13-all-pt1-50k-r1_h022_e0175_t220_nonu_truth.z
epochs: 80
nc: 5
backbone:
 - [-1, 1, 'QuantLinear', 'dense1', {'in_features': 16, 'out_features': 128, 'bias': True, 'input_quant': None, 'bias_quant': None, 'bias_bit_width': 8, 'weight_bit_width': 16, 'weight_quant': 'Int8WeightPerTensorFixedPointPrunePercentile', 'weight_percentile': 0.0}]
 - [-1, 1, 'ReLU', 'relu1', {'inplace': True}]
 - [-1, 1, 'QuantLinear', 'dense2', {'in_features': 128, 'out_features': 64, 'bias': True, 'input_quant': None, 'bias_quant': None, 'bias_bit_width': 8, 'weight_bit_width': 16, 'weight_quant': 'Int8WeightPerTensorFixedPointPrunePercentile', 'weight_percentile': 0.0}]
 - [-1, 1, 'ReLU', 'relu2', {'inplace': True}]
 - [-1, 1, 'QuantLinear', 'dense3', {'in_features': 64, 'out_features': 64, 'bias': True,  'input_quant': None, 'bias_quant': None, 'bias_bit_width': 8, 'weight_bit_width': 16, 'weight_quant': 'Int8WeightPerTensorFixedPointPrunePercentile', 'weight_percentile': 0.0}]
 - [-1, 1, 'ReLU', 'relu3', {'inplace': True}]
 - [-1, 1, 'QuantLinear', 'dense4', {'in_features': 64, 'out_features': 64, 'bias': True,  'input_quant': None, 'bias_quant': None, 'bias_bit_width': 8, 'weight_bit_width': 16, 'weight_quant': 'Int8WeightPerTensorFixedPointPrunePercentile', 'weight_percentile': 0.0}]
 - [-1, 1, 'ReLU', 'relu4', {'inplace': True}]
 - [-1, 1, 'QuantLinear', 'dense5', {'in_features': 64, 'out_features': 5, 'bias': True,  'input_quant': None, 'bias_quant': None, 'bias_bit_width': 8, 'weight_bit_width': 16, 'weight_quant': 'Int8WeightPerTensorFixedPointPrunePercentile', 'weight_percentile': 0.0}]
 - [-1, 1, 'Softmax', 'softmax', {'dim': 1}]
