# This is a configuration file for the ResNet-18 model
name: "resnet50"

# Dataset Params
dataset: "imagenet"
train_path: "tmp/imagenet/train"
test_path: "tmp/imagenet/val"
num_workers: 16
distributed: False
batch_size: [128,128] # train, test

# Training Params
epochs: 80
nc: 1000 # number of classes

backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv2d, "conv1", {'in_channels': 3, 'out_channels': 64, 'kernel_size': 7, 'stride': 2, 'padding': 3, 'dilation': 1, 'groups': 1, 'bias': False}]
  - [-1, 1, BatchNorm2d, "bn1", {'num_features': 64, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
  - [-1, 1, ReLU, "relu", {'inplace': True}]
  - [-1, 1, MaxPool2d, "maxpool", {'kernel_size': 3, 'stride': 2, 'padding': 1, 'dilation': 1, 'return_indices': False, 'ceil_mode': False}]
  - layer1:
      - Bottleneck:
        - [-1, 1, Conv2d, "conv1", {'in_channels': 64, 'out_channels': 64, 'kernel_size': 1, 'stride': 1, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn1", {'num_features': 64, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, Conv2d, "conv2", {'in_channels': 64, 'out_channels': 64, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn2", {'num_features': 64, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, Conv2d, "conv3", {'in_channels': 64, 'out_channels': 256, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn3", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, ReLU, "relu", {'inplace': True}]
        - downsample:
          - [-1, 1, Conv2d, "0", {'in_channels': 64, 'out_channels': 256, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
          - [-1, 1, BatchNorm2d, "1", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
      - Bottleneck:
        - [-1, 1, Conv2d, "conv1", {'in_channels': 256, 'out_channels': 64, 'kernel_size': 1, 'stride': 1, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn1", {'num_features': 64, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, Conv2d, "conv2", {'in_channels': 64, 'out_channels': 64, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn2", {'num_features': 64, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, Conv2d, "conv3", {'in_channels': 64, 'out_channels': 256, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn3", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, ReLU, "relu", {'inplace': True}]
      - Bottleneck:
        - [-1, 1, Conv2d, "conv1", {'in_channels': 256, 'out_channels': 64, 'kernel_size': 1, 'stride': 1, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn1", {'num_features': 64, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, Conv2d, "conv2", {'in_channels': 64, 'out_channels': 64, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn2", {'num_features': 64, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, Conv2d, "conv3", {'in_channels': 64, 'out_channels': 256, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn3", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, ReLU, "relu", {'inplace': True}]
  - layer2:
      - Bottleneck:
        - [-1, 1, Conv2d, "conv1", {'in_channels': 256, 'out_channels': 128, 'kernel_size': 1, 'stride': 1, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn1", {'num_features': 128, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, Conv2d, "conv2", {'in_channels': 128, 'out_channels': 128, 'kernel_size': 3, 'stride': 2, 'padding': 1, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn2", {'num_features': 128, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, Conv2d, "conv3", {'in_channels': 128, 'out_channels': 512, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
        - [-1, 1, BatchNorm2d, "bn3", {'num_features': 512, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - [-1, 1, ReLU, "relu", {'inplace': True}]
        - downsample:
          - [-1, 1, Conv2d, "0", {'in_channels': 256, 'out_channels': 512, 'kernel_size': 1, 'stride': 2, 'padding': 0, 'bias': False}]
          - [-1, 1, BatchNorm2d, "1", {'num_features': 512, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
      - Bottleneck:
          - [-1, 1, Conv2d, "conv1", {'in_channels': 512, 'out_channels': 128, 'kernel_size': 1, 'stride': 1, 'bias': False}]
          - [-1, 1, BatchNorm2d, "bn1", {'num_features': 128, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
          - [-1, 1, Conv2d, "conv2", {'in_channels': 128, 'out_channels': 128, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
          - [-1, 1, BatchNorm2d, "bn2", {'num_features': 128, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
          - [-1, 1, Conv2d, "conv3", {'in_channels': 128, 'out_channels': 512, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
          - [-1, 1, BatchNorm2d, "bn3", {'num_features': 512, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
          - [-1, 1, ReLU, "relu", {'inplace': True}]
      - Bottleneck:
          - [-1, 1, Conv2d, "conv1", {'in_channels': 512, 'out_channels': 128, 'kernel_size': 1, 'stride': 1, 'bias': False}]
          - [-1, 1, BatchNorm2d, "bn1", {'num_features': 128, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
          - [-1, 1, Conv2d, "conv2", {'in_channels': 128, 'out_channels': 128, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
          - [-1, 1, BatchNorm2d, "bn2", {'num_features': 128, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
          - [-1, 1, Conv2d, "conv3", {'in_channels': 128, 'out_channels': 512, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
          - [-1, 1, BatchNorm2d, "bn3", {'num_features': 512, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
          - [-1, 1, ReLU, "relu", {'inplace': True}]
      - Bottleneck:
          - [-1, 1, Conv2d, "conv1", {'in_channels': 512, 'out_channels': 128, 'kernel_size': 1, 'stride': 1, 'bias': False}]
          - [-1, 1, BatchNorm2d, "bn1", {'num_features': 128, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
          - [-1, 1, Conv2d, "conv2", {'in_channels': 128, 'out_channels': 128, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
          - [-1, 1, BatchNorm2d, "bn2", {'num_features': 128, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
          - [-1, 1, Conv2d, "conv3", {'in_channels': 128, 'out_channels': 512, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
          - [-1, 1, BatchNorm2d, "bn3", {'num_features': 512, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
          - [-1, 1, ReLU, "relu", {'inplace': True}]
  - layer3:
        - Bottleneck:
            - [-1, 1, Conv2d, "conv1", {'in_channels': 512, 'out_channels': 256, 'kernel_size': 1, 'stride': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn1", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv2", {'in_channels': 256, 'out_channels': 256, 'kernel_size': 3, 'stride': 2, 'padding': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn2", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv3", {'in_channels': 256, 'out_channels': 1024, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn3", {'num_features': 1024, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, ReLU, "relu", {'inplace': True}]
            - downsample:
                - [-1, 1, Conv2d, "0", {'in_channels': 512, 'out_channels': 1024, 'kernel_size': 1, 'stride': 2, 'padding': 0, 'bias': False}]
                - [-1, 1, BatchNorm2d, "1", {'num_features': 1024, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - Bottleneck:
            - [-1, 1, Conv2d, "conv1", {'in_channels': 1024, 'out_channels': 256, 'kernel_size': 1, 'stride': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn1", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv2", {'in_channels': 256, 'out_channels': 256, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn2", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv3", {'in_channels': 256, 'out_channels': 1024, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn3", {'num_features': 1024, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, ReLU, "relu", {'inplace': True}]
        - Bottleneck:
            - [-1, 1, Conv2d, "conv1", {'in_channels': 1024, 'out_channels': 256, 'kernel_size': 1, 'stride': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn1", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv2", {'in_channels': 256, 'out_channels': 256, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn2", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv3", {'in_channels': 256, 'out_channels': 1024, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn3", {'num_features': 1024, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, ReLU, "relu", {'inplace': True}]
        - Bottleneck:
            - [-1, 1, Conv2d, "conv1", {'in_channels': 1024, 'out_channels': 256, 'kernel_size': 1, 'stride': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn1", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv2", {'in_channels': 256, 'out_channels': 256, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn2", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv3", {'in_channels': 256, 'out_channels': 1024, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn3", {'num_features': 1024, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, ReLU, "relu", {'inplace': True}]
        - Bottleneck:
            - [-1, 1, Conv2d, "conv1", {'in_channels': 1024, 'out_channels': 256, 'kernel_size': 1, 'stride': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn1", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv2", {'in_channels': 256, 'out_channels': 256, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn2", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv3", {'in_channels': 256, 'out_channels': 1024, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn3", {'num_features': 1024, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, ReLU, "relu", {'inplace': True}]
        - Bottleneck:
            - [-1, 1, Conv2d, "conv1", {'in_channels': 1024, 'out_channels': 256, 'kernel_size': 1, 'stride': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn1", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv2", {'in_channels': 256, 'out_channels': 256, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn2", {'num_features': 256, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv3", {'in_channels': 256, 'out_channels': 1024, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn3", {'num_features': 1024, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, ReLU, "relu", {'inplace': True}]
  - layer4:
        - Bottleneck:
            - [-1, 1, Conv2d, "conv1", {'in_channels': 1024, 'out_channels': 512, 'kernel_size': 1, 'stride': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn1", {'num_features': 512, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv2", {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 2, 'padding': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn2", {'num_features': 512, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv3", {'in_channels': 512, 'out_channels': 2048, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn3", {'num_features': 2048, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, ReLU, "relu", {'inplace': True}]
            - downsample:
                - [-1, 1, Conv2d, "0", {'in_channels': 1024, 'out_channels': 2048, 'kernel_size': 1, 'stride': 2, 'padding': 0, 'bias': False}]
                - [-1, 1, BatchNorm2d, "1", {'num_features': 2048, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
        - Bottleneck:
            - [-1, 1, Conv2d, "conv1", {'in_channels': 2048, 'out_channels': 512, 'kernel_size': 1, 'stride': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn1", {'num_features': 512, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv2", {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn2", {'num_features': 512, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv3", {'in_channels': 512, 'out_channels': 2048, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn3", {'num_features': 2048, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, ReLU, "relu", {'inplace': True}]
        - Bottleneck:
            - [-1, 1, Conv2d, "conv1", {'in_channels': 2048, 'out_channels': 512, 'kernel_size': 1, 'stride': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn1", {'num_features': 512, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv2", {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn2", {'num_features': 512, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, Conv2d, "conv3", {'in_channels': 512, 'out_channels': 2048, 'kernel_size': 1, 'stride': 1, 'padding': 0, 'bias': False}]
            - [-1, 1, BatchNorm2d, "bn3", {'num_features': 2048, 'eps': 0.00001, 'momentum': 0.1, 'affine': True, 'track_running_stats': True}]
            - [-1, 1, ReLU, "relu", {'inplace': True}]
  - [-1, 1, AdaptiveAvgPool2d, "avgpool", {'output_size': 1}]
  - [-1, 1, Linear, "fc", {'in_features': 2048, 'out_features': 1000, 'bias': True}]