# This is a configuration file for the ResNet-18 model
name: "vgg19"

# Dataset Params
dataset: "imagenet"
train_path: "/Users/mmecik/datasets/imagenet/train"
test_path: "/Users/mmecik/datasets/imagenet/val"
num_workers: 16
distributed: False
batch_size: [128,128] # train, test

# Training Params
epochs: 80
nc: 1000 # number of classes

backbone:
  - features:
    - [-1, 1, Conv2d, "0", {'in_channels':3,'out_channels': 64,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "1", {'inplace':True}]
    - [-1, 1, Conv2d, "2", {'in_channels':64,'out_channels': 64,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "3", {'inplace':True}]
    - [-1, 1, MaxPool2d, "4", {'kernel_size':2, 'stride':2, 'padding':0, 'dilation':1, 'ceil_mode':False}]
    - [-1, 1, Conv2d, "5", {'in_channels':64,'out_channels': 128,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "6", {'inplace':True}]
    - [-1, 1, Conv2d, "7", {'in_channels':128,'out_channels': 128,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "8", {'inplace':True}]
    - [-1, 1, MaxPool2d, "9", {'kernel_size':2, 'stride':2, 'padding':0, 'dilation':1, 'ceil_mode':False}]
    - [-1, 1, Conv2d, "10", {'in_channels':128,'out_channels': 256,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "11", {'inplace':True}]
    - [-1, 1, Conv2d, "12", {'in_channels':256,'out_channels': 256,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "13", {'inplace':True}]
    - [-1, 1, Conv2d, "14", {'in_channels':256,'out_channels': 256,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "15", {'inplace':True}]
    - [-1, 1, Conv2d, "16", {'in_channels':256,'out_channels': 256,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "17", {'inplace':True}]
    - [-1, 1, MaxPool2d, "18", {'kernel_size':2, 'stride':2, 'padding':0, 'dilation':1, 'ceil_mode':False}]
    - [-1, 1, Conv2d, "19", {'in_channels':256,'out_channels': 512,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "20", {'inplace':True}]
    - [-1, 1, Conv2d, "21", {'in_channels':512,'out_channels': 512,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "22", {'inplace':True}]
    - [-1, 1, Conv2d, "23", {'in_channels':512,'out_channels': 512,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "24", {'inplace':True}]
    - [-1, 1, Conv2d, "25", {'in_channels':512,'out_channels': 512,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "26", {'inplace':True}]
    - [-1, 1, MaxPool2d, "27", {'kernel_size':2, 'stride':2, 'padding':0, 'dilation':1, 'ceil_mode':False}]
    - [-1, 1, Conv2d, "28", {'in_channels':512,'out_channels': 512,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "29", {'inplace':True}]
    - [-1, 1, Conv2d, "30", {'in_channels':512,'out_channels': 512,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "31", {'inplace':True}]
    - [-1, 1, Conv2d, "32", {'in_channels':512,'out_channels': 512,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "33", {'inplace':True}]
    - [-1, 1, Conv2d, "34", {'in_channels':512,'out_channels': 512,'kernel_size':3, 'stride':1, 'padding':1, 'bias':False}]
    - [-1, 1, ReLU, "35", {'inplace':True}]
    - [-1, 1, MaxPool2d, "36", {'kernel_size':2, 'stride':2, 'padding':0, 'dilation':1, 'ceil_mode':False}]
  - [-1, 1, AdaptiveAvgPool2d, "0", {'output_size':7}]
  - classifier:
      - [-1, 1, Linear, "0", {'in_features':25088,'out_features':4096,'bias':True}]
      - [-1, 1, ReLU, "1", {'inplace':True}]
      - [-1, 1, Dropout, "2", {'p':0.5,'inplace':False}]
      - [-1, 1, Linear, "3", {'in_features':4096,'out_features':4096,'bias':True}]
      - [-1, 1, ReLU, "4", {'inplace':True}]
      - [-1, 1, Dropout, "5", {'p':0.5,'inplace':False}]
      - [-1, 1, Linear, "6", {'in_features':4096,'out_features':1000,'bias':True}]
      - [-1, 1, Softmax, "7", {'dim':1}]