# This is a configuration file for the ResNet-18 model
name: "vgg19"

# Dataset Params
dataset: "imagenet"
train_path: "tmp/imagenet/train"
test_path: "tmp/imagenet/val"
num_workers: 1
distributed: False
batch_size: [16, 16] # train, test

# Training Params
epochs: 80
nc: 1000 # number of classes

backbone: 
  - features: 
    - [-1, 1, QuantConv2d, "0", {'in_channels': 3, 'out_channels': 64, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "1", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantConv2d, "2", {'in_channels': 64, 'out_channels': 64, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "3", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantMaxPool2d, "4", {'kernel_size': 2, 'stride': 2, 'padding': 0, 'dilation': 1, 'ceil_mode': False}]
    - [-1, 1, QuantConv2d, "5", {'in_channels': 64, 'out_channels': 128, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "6", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': ¹16}]
    - [-1, 1, QuantConv2d, "7", {'in_channels': 128, 'out_channels': 128, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "8", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantMaxPool2d, "9", {'kernel_size': 2, 'stride': 2, 'padding': 0, 'dilation': 1, 'ceil_mode': True}]
    - [-1, 1, QuantConv2d, "10", {'in_channels': 128, 'out_channels': 256, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "11", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantConv2d, "12", {'in_channels': 256, 'out_channels': 256, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "13", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantConv2d, "14", {'in_channels': 256, 'out_channels': 256, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "15", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantConv2d, "16", {'in_channels': 256, 'out_channels': 256, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "17", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantMaxPool2d, "18", {'kernel_size': 2, 'stride': 2, 'padding': 0, 'dilation': 1, 'ceil_mode': True}]
    - [-1, 1, QuantConv2d, "19", {'in_channels': 256, 'out_channels': 512, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "20", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantConv2d, "21", {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "22", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantConv2d, "23", {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "24", {'inplace0': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantConv2d, "25", {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "26", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantMaxPool2d, "27", {'kernel_size': 2, 'stride': 2, 'padding': 0, 'dilation': 1, 'ceil_mode': True}]
    - [-1, 1, QuantConv2d, "28", {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "29", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantConv2d, "30", {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "31", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantConv2d, "32", {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "33", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantConv2d, "34", {'in_channels': 512, 'out_channels': 512, 'kernel_size': 3, 'stride': 1, 'padding': 1, 'bias': True, 'weight_bit_width': 8}]
    - [-1, 1, QuantReLU, "35", {'inplace': True, 'return_quant_tensor': True, 'output_bit_width': 8}]
    - [-1, 1, QuantMaxPool2d, "36", {'kernel_size': 2, 'stride': 2, 'padding': 0, 'dilation': 1, 'ceil_mode': True}]
  - [-1, 1, TruncAdaptiveAvgPool2d, "avgpool", {'output_size': 7}]
  - classifier: 
      - [-1, 1, QuantLinear, "0", {'in_features': 25088, 'out_features': 4096, 'bias': True}]
      - [-1, 1, QuantReLU, "1", {'inplace': True}]
      - [-1, 1, QuantDropout, "2", {'p': 0.5}]
      - [-1, 1, QuantLinear, "3", {'in_features': 4096, 'out_features': 4096, 'bias': True}]
      - [-1, 1, QuantReLU, "4", {'inplace': True}]
      - [-1, 1, QuantDropout, "5", {'p': 0.5}]
      - [-1, 1, QuantLinear, "6", {'in_features': 4096, 'out_features': 1000, 'bias': True}]